version: '3'
services:
  rest-api:
    build: .
    container_name: movie-recommendations
    restart: on-failure
    ports:
      - 8080:80
    volumes:
      - ./src:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80

  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
